version: '3'
services:
  mysql_dev:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=graphql
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    expose:
      - '3306'
    ports:
      - '3306:3306'
